### ISSUE TITLE
resource is hidden by a resource

### ISSUE THREAD

**Issue by sassouqui1** [rollerworks/RollerworksMultiUserBundle#89]
i have two user-system and each one have its own table in database. so i'm trying to override the template of each user-system so that the "action" in <form> change with every user-system
so i'm trying the b) method "Create A Child Bundle And Override Template"  but i got this error : 

"/var/www/html/test/app/Resources/RollerworksMultiUserBundle/views/UserBundle/Registration/regis  
  ter_content.html.twig" resource is hidden by a resource from the "GAGVendeurBundle" derived bund  
  le. Create a "/var/www/html/test/app/Resources/GAGVendeurBundle/views/UserBundle/Registration/register_content.html.twig" file to override the bundle resource

and when i create the "/var/www/html/test/app/Resources/GAGVendeurBundle/views/UserBundle/Registration/register_content.html.twig" file, it overrdide all the user-systeme templates

help me plz

**Comment by sstok** [comment]
First of sorry for the late reply,

Its hard to determine if this is a bug in RollerworksMultiUserBundle bundle or a wrong usage.
Can you provide more details and if possible a Forked Symfony-standard edition to demonstrate the problem.

Are you setting the RollerworksMultiUserBundle as a parent of your own bundle?
Because that is what the error seems to be saying.
